#!/usr/bin/env sh
# abort on errors
set -e

# stash unstaged changes
git stash


# build for production
npm run production

# navigate into the build output directory
cd build_production

# if you are deploying to a custom domain
# echo 'yourcustomdomain.com' > CNAME

# initialise git repo in the build directory & commit
git init
git add -A
git commit -m 'deploy'

# ssh access hai?
# if you are deploying to https://<USERNAME>.github.io
git push -f git@github.com:vikashprajapati/vikashprajapati.github.io.git master

# if you are deploying to https://<USERNAME>.github.io/<REPO>
#  git push -f git@github.com:<USERNAME>/<REPO> master:gh-pages
cd -

git stash pop